Repository jitacm/30_days_java-Java-Plugin-, pull requests merged in 2025-08, with the labels that each got.

#3 Added Enhanced Tools Menu And Fixed Bug
  Java Plugin/editor/api/Plugin.class
  Java Plugin/editor/api/Plugin.java
  Java Plugin/editor/app/Editor$1.class
  Java Plugin/editor/app/Editor$2.class
  Java Plugin/editor/app/Editor$3.class
  Java Plugin/editor/app/Editor.class
  Java Plugin/editor/app/Editor.java
  Java Plugin/plugins/touppercase.jar
  Java Plugin/plugins/touppercase/ToUppercasePlugin.class
  Java Plugin/plugins/touppercase/ToUppercasePlugin.java
  Java Plugin/plugins/wordcount.jar
  Java Plugin/plugins/wordcount/WordCountPlugin.class
  Java Plugin/plugins/wordcount/WordCountPlugin.java
Labels: 30daysdevchallenge, jitacm, feature, level-4

#6 Added Spell Check Plugin to Modern Plugin Text Editor
  JavaPlugin/editor/api/Plugin.class
  JavaPlugin/editor/app/Editor$1.class
  JavaPlugin/editor/app/Editor.class
  JavaPlugin/plugins/spellcheck.jar
  JavaPlugin/plugins/spellcheck/SpellCheckPlugin.class
  JavaPlugin/plugins/spellcheck/SpellCheckPlugin.java
  JavaPlugin/plugins/touppercase.jar
  JavaPlugin/plugins/touppercase/ToUppercasePlugin.class
  JavaPlugin/plugins/wordcount.jar
  JavaPlugin/plugins/wordcount/WordCountPlugin.class
Labels: 30daysdevchallenge, jitacm, feature, level-2

#14 Adds New Text Statistics Plugin
  JavaPlugin/plugins/multicaret.jar
  JavaPlugin/plugins/textstats/TextStatsPlugin.java
Labels: 30daysdevchallenge, jitacm, feature, level-2

#20 Added advanced Find and Replace functionality to Editor
  JavaPlugin/editor/api/Plugin.class
  JavaPlugin/editor/app/Editor$1.class
  JavaPlugin/editor/app/Editor$2.class
  JavaPlugin/editor/app/Editor$3.class
  JavaPlugin/editor/app/Editor.class
  JavaPlugin/editor/app/Editor.java
Labels: 30daysdevchallenge, feature, level-4

#22 Implementing Live Markdown/HTML Preview Feature #21
  JavaPlugin/editor/app/Editor.java
Labels: 30daysdevchallenge, jitacm, feature, level-3
